"""Build the copy-only prompt from the skill's canonical setup contract."""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / "second-brain/skill/shared-second-brain"
TEMPLATES = ("AGENTS.md", "CLAUDE.md", "index.md", "working-agreement.md", "project.md", "checkpoint.md", "decision.md")

def render():
    parts = ["<!-- Generated by scripts/build_prompt.py; edit the skill setup reference/templates. -->\n",
             "# Shared Second Brain setup prompt\n\nSet up shared Obsidian project memory for my coding project using the procedure and embedded templates below. Ask for any missing project/vault choices. No skill installation or access to Labstack is needed.\n",
             (SKILL / "references/setup.md").read_text(encoding="utf-8").rstrip()]
    for name in TEMPLATES:
        parts.append(f"## Embedded template: {name}\n\n```markdown\n" + (SKILL / "templates" / name).read_text(encoding="utf-8").rstrip() + "\n```")
    return "\n\n".join(parts) + "\n"

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "second-brain/brain-prompt.md"
    expected = render()
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != expected:
            raise SystemExit("Setup prompt is stale. Run python scripts/build_prompt.py")
        print("Standalone prompt matches canonical skill sources.")
    else:
        target.write_text(expected, encoding="utf-8", newline="\n")
        print("Built second-brain/brain-prompt.md")

if __name__ == "__main__":
    main()
